name: IPFS Kubo
services:
  kubo:
    image: ipfs/kubo:latest
    container_name: ipfs_host
    networks:
      - kubo
    restart: always
    volumes:
      - /home/codev/ipfs/export:/export # replace /home/codev/ipfs/export with your own directory
      - /home/codev/ipfs/data:/data/ipfs # replace /home/codev/ipfs/data with your own directory
    ports:
      - 4001:4001
      - 4001:4001/udp
      - 0.0.0.0:8080:8080
      - 0.0.0.0:5001:5001
    expose:
      - "4001"
      - "5001"
      - "8080"
    # command: 
    #   - config Routing.Type dhtserver
    #   - config --json Discovery.MDNS
    #   - config profile apply server
    #   - config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
    #   - config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT","POST"]'
networks:
  kubo:
    name: kubo
    driver: bridge
    external: true