version: '3.8'

services:
  kubo:
    image: ipfs/kubo:latest
    container_name: ipfs_host
    networks:
      - kubo
    restart: always
    volumes:
      - /home/codev/ipfs/export:/export
      - /home/codev/ipfs/data:/data/ipfs
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "8080:8080"
      - "5001:5001"

networks:
  kubo:
    name: kubo
    driver: bridge
    external: true