version: '3.8'

services:
  app:
    environment:
      IPFS_PROFILE: server
      IPFS_ENABLE_RELAY: true
      IPFS_AUTO_RELAY: true
      IPFS_DISABLE_GC: true
    restart: always
    volumes:
      - /home/codev/ipfs/export:/export
      - /home/codev/ipfs/data:/data/ipfs
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "8080:8080"
      - "5001:5001"
    build: .
