version: '3.7'
services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs_node
    ports:
      - 4001:4001             # Swarm
      - 4001:4001/udp         # Swarm UDP
      - 0.0.0.0:8080:8080     # Gateway access (private, optional)
      - 0.0.0.0:5001:5001     # API
    environment:
      IPFS_PROFILE: server
    volumes:
      - ./ipfs_data:/data/ipfs
      - ./scripts:/scripts
    entrypoint: /bin/sh
    command: -c 'sh /scripts/configure_ipfs.sh && ipfs daemon --migrate=true --enable-gc'
    restart: always
    networks:
      - ipfs
networks:
  ipfs:
    name: ipfs
    driver: bridge
    external: true
