version: '3.7'
name: IPFS Kubo
services:
  kubo:
    build: .
    image: ipfs/kubo:latest
    container_name: ipfs_host
    environment:
      IPFS_PROFILE: server
    networks:
      - kubo
    restart: always
    volumes:
      - /home/codev/ipfs/export:/export
      - /home/codev/ipfs/data:/data/ipfs
    ports:
      - 4001:4001
      - 4001:4001/udp
      - 0.0.0.0:8080:8080
      - 0.0.0.0:5001:5001
    expose:
      - "4001"
      - "5001"
      - "8080"
networks:
  kubo:
    name: kubo
    driver: bridge
    external: true