name: IPFS Kubo
services:
  kubo:
    image: ipfs/kubo:latest
    container_name: ipfs_host
    restart: always
    volumes:
      - /home/codev/ipfs/export:/export # replace /home/codev/ipfs/export with your own directory
      - /home/codev/ipfs/data:/data/ipfs # replace /home/codev/ipfs/data with your own directory
    ports:
      - 4001:4001
      - 4001:4001/udp
      - 0.0.0.0:8080:8080
      - 0.0.0.0:5001:5001
    expose:
      - "4001"
      - "5001"
      - "8080"
    commands: >
      config --json API.HTTPHeaders.Access-Control-Allow-Origin '["http://192.168.33.100:5001","http://localhost:3000","http://127.0.0.1:5001","https://webui.ipfs.io"]' &&
      config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT","POST"]'