version: '3.7'
services:
  app:
    build: .                       # Membangun image menggunakan Dockerfile
    container_name: ipfs_node
    ports:
      - 0.0.0.0:4001:4001                  # Swarm TCP
      - 0.0.0.0:4001:4001/udp              # Swarm UDP
      - 0.0.0.0:8080:8080                  # Gateway
      - 0.0.0.0:5001:5001                  # API
    environment:
      IPFS_PROFILE: server
    volumes:
      - /home/codev/ipfs_data:/data/ipfs     # Volume untuk data IPFS
    restart: always
