version: '3.7'
services:
  app:
    build: .
    container_name: ipfs_node
    ports:
      - 4001:4001
      - 4001:4001/udp
      - 8080:8080
      - 5001:5001
    expose:
      - "4001"
      - "5001"
      - "8080"
    environment:
      IPFS_PROFILE: server
      IPFS_ENABLE_RELAY: true
      IPFS_AUTO_RELAY: true
      IPFS_DISABLE_GC: false
    volumes:
      - /home/codev/ipfs_data:/data/ipfs
    restart: always
