version: '3.8'

services:
  kubo:
    container_name: ipfs_host
    networks:
      - kubo
    restart: always
    volumes:
      - /home/codev/ipfs/export:/export
      - /home/codev/ipfs/data:/data/ipfs
    build: .
    environment:
      IPFS_PROFILE: server
      IPFS_ENABLE_RELAY: true
      IPFS_AUTO_RELAY: true
      IPFS_DISABLE_GC: true

networks:
  kubo:
    name: kubo
    driver: bridge
    external: true
