version: '3.7'
services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs_node
    ports:
      - 4001:4001             # Swarm
      - 4001:4001/udp         # Swarm UDP
      - 127.0.0.1:8080:8080   # Gateway access (private, optional)
      - 5001:5001             # API
    environment:
      IPFS_PROFILE: server
    command: [
      daemon,
      --migrate=true,
      --enable-gc
    ]
    restart: always
    networks:
      - ipfs
    entrypoint: "/bin/sh -c '/scripts/configure_ipfs.sh && ipfs daemon'"
    volumes:
      - /home/codev/ipfs/export:/export   # replace /home/codev/ipfs/export with your own directory
      - /home/codev/ipfs/data:/data/ipfs  # replace /home/codev/ipfs/data with your own directory
      - /home/codev/ipfs/scripts:/scripts # replace /home/codev/ipfs/scripts with your own directory
networks:
  ipfs:
    name: ipfs
    driver: bridge
    external: true