version: '3.7'
services:
  ipfs:
    build: .                       # Membangun image menggunakan Dockerfile
    container_name: ipfs_node
    ports:
      - 4001:4001                  # Swarm TCP
      - 4001:4001/udp              # Swarm UDP
      - 8080:8080                  # Gateway
      - 5001:5001                  # API
    environment:
      IPFS_PROFILE: server
    volumes:
      - ./ipfs_data:/data/ipfs     # Volume untuk data IPFS
    restart: always
    networks:
      - ipfs
networks:
  ipfs:
    name: ipfs
    driver: bridge
    external: true
