version: '3.7'
services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs_node
    ports:
      - "4001:4001"           # Swarm TCP
      - "4001:4001/udp"       # Swarm UDP
      - "0.0.0.0:8080:8080"   # Gateway access (public, optional)
      - "0.0.0.0:5001:5001"   # API
    environment:
      IPFS_PROFILE: server
    command: [
      "daemon",
      "--migrate=true",
      "--enable-gc"
    ]
    restart: always
    networks:
      - ipfs
    entrypoint: "/bin/sh -c 'ipfs init && /scripts/configure_ipfs.sh && ipfs daemon'"
    volumes:
      - ./ipfs_data:/data/ipfs
      - ./scripts:/scripts
networks:
  ipfs:
    name: ipfs
    driver: bridge
    external: true   # Pastikan network 'ipfs' sudah dibuat secara eksternal atau hapus baris ini jika tidak diperlukan
